
version: '3.8'

services:

  ganache1:
    build: .
    ports:
      - "8545:8545"
    command: ganache --chain.chainId 1234 --chain.networkId 1234 --host 0.0.0.0 --port 8545

  ganache2:
    build: .
    ports:
      - "8546:8545"
    command: ganache --chain.chainId 5678 --chain.networkId 5678 --host 0.0.0.0 --port 8545
